// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Snitcher.Repository.Contexts;

#nullable disable

namespace Snitcher.Repository.Migrations
{
    [DbContext(typeof(SnitcherDbContext))]
    partial class SnitcherDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Snitcher.Core.Entities.MetadataEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsReadOnly")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelatedEntityType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Scope")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("string");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("IX_MetadataEntries_Category");

                    b.HasIndex("RelatedEntityId")
                        .HasDatabaseName("IX_MetadataEntries_RelatedEntityId");

                    b.HasIndex("RelatedEntityType")
                        .HasDatabaseName("IX_MetadataEntries_RelatedEntityType");

                    b.HasIndex("Scope", "Key", "RelatedEntityId")
                        .IsUnique()
                        .HasDatabaseName("IX_MetadataEntries_Scope_Key_RelatedEntityId");

                    b.ToTable("MetadataEntries", null, t =>
                        {
                            t.HasCheckConstraint("CK_MetadataEntries_RelatedEntity_Consistency", "(RelatedEntityId IS NULL AND RelatedEntityType IS NULL) OR (RelatedEntityId IS NOT NULL AND RelatedEntityType IS NOT NULL)");

                            t.HasCheckConstraint("CK_MetadataEntries_Scope_Valid", "Scope >= 0 AND Scope <= 4");
                        });
                });

            modelBuilder.Entity("Snitcher.Core.Entities.Namespace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Depth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastAnalyzedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentNamespaceId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Depth")
                        .HasDatabaseName("IX_Namespaces_Depth");

                    b.HasIndex("ParentNamespaceId")
                        .HasDatabaseName("IX_Namespaces_ParentNamespaceId");

                    b.HasIndex("WorkspaceId", "FullName")
                        .IsUnique()
                        .HasDatabaseName("IX_Namespaces_WorkspaceId_FullName");

                    b.ToTable("Namespaces", (string)null);
                });

            modelBuilder.Entity("Snitcher.Core.Entities.ProjectEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastAnalyzedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("NamespaceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NamespaceId")
                        .HasDatabaseName("IX_Projects_NamespaceId");

                    b.HasIndex("Path")
                        .HasDatabaseName("IX_Projects_Path");

                    b.HasIndex("WorkspaceId", "Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Projects_WorkspaceId_Name");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("Snitcher.Core.Entities.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsDefault")
                        .HasDatabaseName("IX_Workspaces_IsDefault");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Workspaces_Name");

                    b.ToTable("Workspaces", (string)null);
                });

            modelBuilder.Entity("Snitcher.Core.Entities.Namespace", b =>
                {
                    b.HasOne("Snitcher.Core.Entities.Namespace", "ParentNamespace")
                        .WithMany("ChildNamespaces")
                        .HasForeignKey("ParentNamespaceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Snitcher.Core.Entities.Workspace", "Workspace")
                        .WithMany("Namespaces")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentNamespace");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Snitcher.Core.Entities.ProjectEntity", b =>
                {
                    b.HasOne("Snitcher.Core.Entities.Namespace", "Namespace")
                        .WithMany("Projects")
                        .HasForeignKey("NamespaceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Snitcher.Core.Entities.Workspace", "Workspace")
                        .WithMany("Projects")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Namespace");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Snitcher.Core.Entities.Namespace", b =>
                {
                    b.Navigation("ChildNamespaces");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("Snitcher.Core.Entities.Workspace", b =>
                {
                    b.Navigation("Namespaces");

                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
